config/routes.rb
Gamecal::Application.routes.draw do

  root 'site#index'

  #Site
  get 'privacy' => 'site#privacy'
  get 'terms' => 'site#terms'
  post '/auth/steam/callback' => 'site#auth_callback'

  get 'friends' => 'site#friends'
  get 'persona' => 'site#persona'


  # Event

  # get 'events' => 'events#index'
  # get 'events/new' => 'events#new'
  # post 'events' => 'events#create'

  resources :events


end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :user_events
  belongs_to :game

end

app/models/events.rb
class Events < ActiveRecord::Base

  belongs_to :user
  belongs_to :user_events
  belongs_to :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :is_authenticated?

  def is_authenticated?
    !!session[:current_user]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index

  end

  def new
    @event = Event.new
  end

  def create
        @event = Event.new(event_params)

    @event.save
    redirect_to @event
  end

  def show

  end

  def event_params
    params.require(:event).permit(:game_id, :owner, :date, :time_start, :time_finish, :friend_id, :email_address, :description)

  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [ :auth_callback ]
  # before_action :is_authenticated?, except: [ :callback ]

  def index
    @events = Event.all
    @events_by_date = @events.group_by(&:date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def auth_callback
    auth = request.env['omniauth.auth']
    session[:current_user] = { :nickname => auth.info['nickname'],
                                          :image => auth.info['image'],
                                          :uid => auth.uid }

    session[:uid] = auth.uid

    redirect_to root_url
  end

  def friends
    response = HTTParty.get("http://api.steampowered.com/ISteamUser/GetFriendList/v0001/?key=#{STEAM_CONFIG['steam_api']}&steamid=#{session[:uid]}&relationship=friend")

    render json: response
  end

  def persona
    url = "http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=#{STEAM_CONFIG['steam_api']}&steamids=#{params[:steamids]}"
    response = HTTParty.get(url)

    render json: response
  end

  def privacy

  end

  def terms

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/site_helper.rb
module SiteHelper

  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sun Mon Tue Wed Thur Fri Sat]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Create Game</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= form_for @event do |f|%>
      <div id="new_event">

 <!-- FIXME - needs to be a collection_select -->
        <div class="form-group" role="form">
          <%= f.text_field :game_id, class: "form-control", placeholder: "Game" %>
        </div>

        <div class="form-group" role="form">
          <%= f.text_field :date, id: "event_date", class: "form-control", placeholder: "Date" %>
        </div>

        <div class="form-inline" role="form">
          <%= f.text_field :time_start, class: "event_time form-control", placeholder: "Start time" %>
          <%= f.text_field :time_finish, class: "event_time form-control", placeholder: "Finish time" %>
        </div>

        <div class="checkbox">
          <%= f.check_box :email_address %>
          <p>Email notification</p>
        </div>

        <div class="form-group" role="form">
          <%= f.text_area :description, size: "40x5", class: "form-control", placeholder: "Description of event"  %>
        </div>

        <div>
          <%= submit_tag :Submit, class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-1">
  </div>

  <div class="col-md-5">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Friends</h3>
      </div>
      <div id="friends-list" class="panel-body friends_list"><ul></ul></div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamecal</title>
    <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", media: "all"%>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header role="banner">
      <nav class="navbar navbar-inverse navbar-fixed" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">GAMECAL</a>
          </div>
          <div class="pull-right">
            <% if is_authenticated? %>
            <% else %>
              <%= link_to image_tag("http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_landing.png"), '/auth/steam' %>
            <% end %>
            <% if session.key? :current_user %>
              Hello <%= session[:current_user][:nickname] %>
            <div class="img-thumbnail">
              <a href="http://steamcommunity.com/"><%= image_tag session[:current_user][:image] %></a>
            </div>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>

  </body>
  <footer>
    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8">
            <div class="pull-left">
              <p>
                <%= link_to "privacy policy", privacy_url%>
                  &bull;
                <%= link_to "terms of use", terms_url%>
                  &bull;
                  &copy; 2014 GameCal
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="pull-right">
              Powered by Steam
              <a href="http://steampowered.com"><img class="steam_logo"><%= image_tag("globalheader_logo.png")%>
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </footer>
</html>

app/views/site/create.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Create Game</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="input-group">
      <input type="text" class="form-control">
      <div class="input-group-btn">
        <button type="button" class="btn btn-primary  dropdown-toggle" data-toggle="dropdown">Game <span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li>Action</li>
        </ul>
      </div>
    </div>

    <form class="form-group" role="form">
      <input type="date" class="form-control">
    </form>

      <input type="text" name="model[published_on]" id="article_published_on">

    <form class="form-inline" role="form">
      <div class="form-group">
        <input type="time" class="form-control">
        <input type="time" class="form-control">
      </div>
    </form>

    <div class="checkbox">
      <label>
        <input type="checkbox" value="">
        Email notification?
      </label>
    </div>

    <form class="form-group" role="form">
      <div class="form-group">
        <textarea class="form-control" rows="3" placeholder="Description of event"></textarea>
      </div>
    </form>

    <div>
      <button type="button" class="btn btn-primary btn-lg">Create Event</button>
    </div>

  </div>

  <div class="col-md-6">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Friends</h3>
      </div>
      <div class="panel-body">
        Select friends here
      </div>
    </div>

  </div>
</div>

app/views/site/event.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Create Game</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="input-group">
      <input type="text" class="form-control">
      <div class="input-group-btn">
        <button type="button" class="btn btn-primary  dropdown-toggle" data-toggle="dropdown">Game <span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li>Action</li>
        </ul>
      </div>
    </div>

    <form class="form-group" role="form">
      <input id="event_date" class="form-control" placeholder="Date">
    </form>


    <form class="form-inline" role="form">
      <input class="form-control event_time" placeholder="Start Time">
      <input class="form-control event_time" placeholder="End Time">
    </form>

    <div class="checkbox">
      <label>
        <input type="checkbox" value="">
          <p>Email notification?</p>
      </label>
    </div>

    <form class="form-group" role="form">
      <div class="form-group">
        <textarea class="form-control" rows="3" placeholder="Description of event"></textarea>
      </div>
    </form>

    <div>
      <button type="button" class="btn btn-primary btn-lg">Create Event</button>
    </div>

  </div>

  <div class="col-md-6">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Friends</h3>
      </div>
      <div class="panel-body">
        Select friends here
      </div>
    </div>

  </div>
</div>

app/views/site/index.html.erb
<!-- <div class="row">
  <div class="col-md-12">
    <div>
    </div>
  </div>
</div> -->


<div class="row">
  <div class="col-md-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Todays Events</h2>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div id="events">
      <h2 id="month">
        <%= link_to "<", date: @date.prev_month %>
        <%= @date.strftime("%B %Y") %>
        <%= link_to ">", date: @date.next_month %>
      </h2>
      <%= calendar @date do |date| %>
        <%= date.day %>
        <% if @events_by_date[date] %>
          <ul>
            <% @events_by_date[date].each do |event| %>
              <li><%= link_to event.name, event %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Friends List</h2>
      </div>
      <div id="friends-list" class="panel-body friends_list"><ul></ul></div>
    </div>
  </div>
</div>

<!-- <div><%= session[:current_user].inspect %></div> -->

app/views/site/privacy.html.erb
 privacy page

app/views/site/terms.html.erb
 terms